from announcement import *
from attendance import *
from audit_log import *
from certificate import *
from department import *
from enums import *
from exam_result import *
from exam import *
from faculty import *
from financial import *
from grade import *
from group import *
from login_history import *
from message import *
from schedule import *
from student import *
from subject import *
from teacher import *